### ISSUE TITLE
KeyError : 'SPOTIFY_USERNAME'

### ISSUE THREAD

**Issue by dark-eraser** [andersonshatch/spotify-connect-device-picker#1]
hi when trying to launch for the first time your script it gives this error 
`` username = os.environ['SPOTIFY_USERNAME']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SPOTIFY_USERNAME'``I tried to rebuild your script but i get the same result. PLease help

**Comment by andersonshatch** [comment]
Hi!

First, it seems you are using Python 2, which is not compatible, this script needs Python 3.6 or higher.


Then, you'll need to set environment variables when running the script, you can either have a file with exports, or run it like this:

`SPOTIFY_USERNAME=yourspotifyusername SPOTIPY_CLIENT_ID=yourclientid SPOTIPY_CLIENT_SECRET=yourclientsecret SPOTIPY_REDIRECT_URI=example.com python3 spotify-connect-device-picker.py`

**Comment by dark-eraser** [comment]
Thank you very much for your help.
