### ISSUE TITLE
some devices don't show up.

### ISSUE THREAD

**Issue by dark-eraser** [andersonshatch/spotify-connect-device-picker#2]
hi there. i've run into another issue which doesn#t seem to be on my side.
When consulting succesfully the devices connected to my spotify account, i've noticed that devices like smart speakers, raspberry pi's and smart TV's don't show up on the connected devices list. I think this could easily be fixed although i don't exactly know how.
What do you think ?? 
Thanks in advance.

**Comment by andersonshatch** [comment]
This script only displays what the Spotify APIs send back, and unfortunately they say it's to be expected that some devices are not returned even when they would be visible in the app's device picker:

> Connect Web API relies on local network connections to discover and interact with some devices.
>
>For example, when:
> - A new device is added to the network
> - A device is in “sleep” mode
> - A device on the local network is currently tied to another user account, or
> - Other reasons specific to the device
>
> As a result, some devices that appear in the Connect picker within the Spotify application may not always be visible or available on the Connect Web API Endpoints.

https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/

... So there is nothing I can change about this 🙁
I think the issue should be reported here: [spotify/web-api](https://github.com/spotify/web-api/issues), but I'm not sure if there is any hope of this changing.

**Comment by dark-eraser** [comment]
Thank you very much for your fast response.
What your saying is really sad because I'm trying to play Spotify on a
headless raspberry pi, which i'm doing successfully by the way. But the
issue I have is that I want to change the device I'm playing on remotely
from the command line and ultimately through a keyboard shortcut. However,
only your script would allow me to do so, but only if it detects the
raspberry pi. I have yet to determine if the issue lies within the nature
of the device or something else. I 've tested it successfully with another
smart speaker, but not a raspberry pi.
I'll come back to you if I make any progress.
